services:
  api:
    image: belrom/credit_api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: credit_api
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - MODEL_PATH=models/nn_model_int8.onnx
    ports:
      - "8000:8000"

  frontend:
    image: belrom/credit_frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: credit_frontend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
