apiVersion: v1
kind: Service
metadata:
  name: credit-api-service
  labels:
    app: credit-api
spec:
  type: ClusterIP
  selector:
    app: credit-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
