name: Rollback Deployment

on:
  workflow_run:
    workflows: ["Monitor"]
    types:
      - completed


jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - name: Skip staging deployment
        run: echo "Rollback deployment is skipped."